all:
  children:
    p0:
      hosts:
        127.0.0.1:
          ansible_user: "root"
          ansible_ssh_private_key_file: <private_key_path>
          role: "P"

          env:
            MODEL_EXTRA_CFG_PATH: "/workspace/omniinfer/tests/test_config/test_config_prefill.json"
            RANKTABLE_SAVE_PATH: "/tmp/ranktable_save_path"
            RANK_TABLE_FILE_PATH: ""
            GLOBAL_RANK_TABLE_FILE_PATH: ""
            PYTORCH_NPU_ALLOC_CONF: "expandable_segments:True"
            SOCKET_IFNAME: enp23s0f3
            API_PORT: 9050
            MASTER_PORT: 8050
            TNG_HOST_COPY: 1
            MODEL_LEN_MAX_PREFILL: 16384
            VLLM_LLMDATADIST_ZMQ_PORT: 5588
            ASCEND_RT_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
            MODEL_PATH: "/data/model/DeepSeek-R1-w8a8-fusion"
            AUTO_USE_UC_MEMORY: 1
            SERVER_IP_LIST: "7.150.13.146,7.150.14.47"
            SERVER_OFFSET: 0
            PREFILL_SERVER_LIST: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
            VLLM_WORKER_MULTIPROC_METHOD: fork
            GLOO_SOCKET_IFNAME: enp23s0f3
            TP_SOCKET_IFNAME: enp23s0f3
            HOST_IP: "7.150.10.171"
            VLLM_USE_V1: 1
            CODE_PATH: "/workspace"
            LOG_PATH: ""
            LOCAL_DECODE_SERVER_IP_LIST: ""  # The IP of current D instance
            GLOBAL_DECODE_SERVER_IP_LIST: "${SERVER_IP_LIST}"  # The IP of all decode instances
            PREFILL_TENSOR_PARALLEL_SIZE: 16
            ROLE: "prefill"
            TASK_QUEUE_ENABLE: 2
            SHLVL: 1
            VLLM_ENABLE_MC2: 1
            DECODE_POD_NUM: "1"
            PREFILL_POD_NUM: "2"
            VLLM_LOGGING_LEVEL: INFO
            KV_RANK: "0"
            OMNI_USE_DSV3: 1
            # ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE: 0
            # ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT: 1
            # ATB_WORKSPACE_MEM_ALLOC_GLOBAL: 0
            # ATB_DEVICE_TILING_BUFFER_BLOCK_NUM: 32
            # ATB_HOME_PATH: /usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
            # ATB_COMPARE_TILING_EVERY_KERNEL: 0
            # ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE: 0
            # ATB_MATMUL_SHUFFLE_K_ENABLE: 1
            # ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE: 1
            # ATB_HOST_TILING_BUFFER_BLOCK_NUM: 128
            # ATB_SHARE_MEMORY_NAME_SUFFIX: ""
            # ATB_OPSRUNNER_SETUP_CACHE_ENABLE: 1
            # ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE: 0
            # ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT: 5
            HCCL_INTRA_PCIE_ENABLE: 0
            HCCL_EXEC_TIMEOUT: 120
            HCCL_BUFFSIZE: 500
            HCCL_CONNECT_TIMEOUT: 120
            HCCL_INTRA_ROCE_ENABLE: 1
            USING_LCCL_COM: 0
            LCCL_PARALLEL: 0
            LCCL_DETERMINISTIC: 0
            # ASDOPS_LOG_TO_FILE: 1
            # ASDOPS_LOG_LEVEL: ERROR
            # ASDOPS_LOG_TO_BOOST_TYPE: atb
            # ASDOPS_LOG_TO_FILE_FLUSH: 0
            # ASDOPS_LOG_TO_STDOUT: 0
            # ASDOPS_LOG_PATH: /root
            # ASDSIP_LOG_LEVEL: INFO
            # ASDSIP_LOG_PATH: /root
            # ASDSIP_LOG_TO_STDOUT: 0
            # ASDSIP_LOG_TO_BOOST_TYPE: asdsip
            # ASDSIP_HOME_PATH: /usr/local/Ascend/nnal/asdsip/latest/
            # ASDSIP_LOG_TO_FILE_FLUSH: 0
            # ASDSIP_LOG_TO_FILE: 0
            TOOLCHAIN_HOME: /usr/local/Ascend/ascend-toolkit/latest/toolkit
            ASCEND_TOOLKIT_HOME: /usr/local/Ascend/ascend-toolkit/latest
            ASCEND_OPP_PATH: /usr/local/Ascend/ascend-toolkit/latest/opp
            ASCEND_AICPU_PATH: /usr/local/Ascend/ascend-toolkit/latest
            ASCEND_HOME_PATH: /usr/local/Ascend/ascend-toolkit/latest
            ASCEND_LAUNCH_BLOCKING: 0
            # HCCL_OP_EXPANSION_MODE: "AIV"

          args:
            num-servers: "1"
            num-dp: "1"
            server-offset: "0"
            model-path: "$MODEL_PATH"
            master-ip: "7.150.13.146"
            max-model-len: "32000"
            master-port: "$MASTER_PORT"
            base-api-port: "$API_PORT"
            tp: "16"
            served-model-name: "deepseek"
            log-dir: "$LOG_DIR"
            kv-transfer-config: >-
              {"kv_connector": "AscendHcclConnectorV1",
              "kv_buffer_device": "npu",
              "kv_role":"$KV_ROLE",
              "kv_rank":$KV_RANK,
              "engine_id":$KV_ENGINE_ID,
              "kv_parallel_size":$KV_PARALLEL_SIZE}
            gpu-util: "0.92"
            additional-config: ""
            extra-args: ""
