all:
  vars:
    ansible_user: root
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o IdentitiesOnly=yes'
    ansible_ssh_private_key_file: /data/00943438/srckey/id_rsa_20251020.pem
    # ansible_password: 'Hw20250815!'
    global_port_base: 7000
    base_api_port: 9000
    proxy_port: 8000
    port_offset:
      P: 0      # Actual port range for group P: 8000-8099
      D: 164    # Actual port range for group D: 8100-8199

  children:
    P:
      hosts:
        p0:
          ansible_host: "7.150.8.102"
          node_rank: 0
          kv_rank: 0
          node_port: "{{ global_port_base + port_offset.P + kv_rank }}"
          api_port: "{{ base_api_port + port_offset.P + kv_rank }}"
          host_ip: "7.150.8.102"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"
        p1:
          # ansible_host: "7.150.15.197"
          ansible_host: "7.150.15.197"
          node_rank: 1
          kv_rank: 0
          node_port: "{{ global_port_base + port_offset.P + kv_rank }}"
          api_port: "{{ base_api_port + port_offset.P + kv_rank }}"
          host_ip: "7.150.8.102"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

    D:
      hosts:
        d0:
          ansible_host: "7.150.12.42"
          node_rank: 0
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "7.150.12.42"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"
        d1:
          ansible_host: "7.150.15.64"
          node_rank: 1
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "7.150.12.42"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"
        d2:
          ansible_host: "7.150.10.173"
          node_rank: 2
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "7.150.12.42"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"
        d3:
          ansible_host: "7.150.12.132"
          node_rank: 3
          node_port: "{{ global_port_base + port_offset.D }}"
          api_port: "{{ base_api_port + port_offset.D + node_rank }}"
          host_ip: "7.150.12.42"
          ascend_rt_visible_devices: "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"

    C:
      hosts:
        c0:
          ansible_host: "7.150.12.42"
          node_rank: 0
          node_port: "{{ proxy_port + node_rank }}"
          role: "C"
